[profile.default]
src = "src"
out = "out"
solc = "0.4.19"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
evm_version = "london"
bytecode_hash = "ipfs"
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15, fail_on_revert = false, call_override = false }
fs_permissions = [{ access = "read", path = "./" }]

[rpc_endpoints]
chronos = "https://auto-evm.chronos.autonomys.xyz/ws"
chronos_wss = "wss://auto-evm.chronos.autonomys.xyz/ws"

[etherscan]
chronos = { key = "${CHRONOS_API_KEY}", url = "https://explorer.auto-evm.chronos.autonomys.xyz/api" }